require("dotenv").config();
const express = require("express");
const path = require("path");
const cookieParser = require("cookie-parser");
const logger = require("morgan");
const indexRouter = require("./routes/index");
const usersRouter = require("./routes/users");
const ratingsRouter = require("./routes/ratings");
const carsRouter = require("./routes/cars");
const carsImageRouter = require("./routes/carsImage");
const carsFeatureRouter = require("./routes/carsFeature");
const cityRouter = require("./routes/city");
const addressRouter = require("./routes/address");
const bookingRouter = require("./routes/booking");
const cors = require("cors");
const app = express();

app.use(logger("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, "public")));
app.use(cors());
app.use("/", indexRouter);
app.use("/users", usersRouter);
app.use("/ratings", ratingsRouter);
app.use("/cars", carsRouter);
app.use("/cars/image", carsImageRouter);
app.use("/cars/feature", carsFeatureRouter);
app.use("/city", cityRouter);
app.use("/address", addressRouter);
app.use("/booking", bookingRouter);
module.exports = app;
